package com.weatherapp.model;

import java.util.HashSet;
import java.util.Set;

public class CountryValidator {

    private static final String[][] COUNTRIES = {
            {"AF", "Afghanistan"},
            {"AL", "Albania"},
            {"DZ", "Algeria"},
            {"AD", "Andorra"},
            {"AO", "Angola"},
            {"AI", "Anguilla"},
            {"AQ", "Antarctica"},
            {"AG", "Antigua and Barbuda"},
            {"SA", "Saudi Arabia"},
            {"AR", "Argentina"},
            {"AM", "Armenia"},
            {"AW", "Aruba"},
            {"AU", "Australia"},
            {"AT", "Austria"},
            {"AZ", "Azerbaijan"},
            {"BS", "Bahamas"},
            {"BH", "Bahrain"},
            {"BD", "Bangladesh"},
            {"BB", "Barbados"},
            {"BE", "Belgium"},
            {"BZ", "Belize"},
            {"BJ", "Benin"},
            {"BM", "Bermuda"},
            {"BT", "Bhutan"},
            {"BY", "Belarus"},
            {"BO", "Bolivia"},
            {"BQ", "Bonaire"},
            {"BA", "Bosnia and Herzegovina"},
            {"BW", "Botswana"},
            {"BR", "Brazil"},
            {"BN", "Brunei Darussalam"},
            {"IO", "British Indian Ocean Territory"},
            {"BG", "Bulgaria"},
            {"BF", "Burkina Faso"},
            {"BI", "Burundi"},
            {"XC", "Ceuta"},
            {"CL", "Chile"},
            {"CN", "China"},
            {"CW", "Curaçao"},
            {"HR", "Croatia"},
            {"CY", "Cyprus"},
            {"TD", "Chad"},
            {"ME", "Montenegro"},
            {"CZ", "Czechia"},
            {"DK", "Denmark"},
            {"DM", "Dominica"},
            {"DO", "Dominican Republic"},
            {"DJ", "Djibouti"},
            {"EG", "Egypt"},
            {"EC", "Ecuador"},
            {"ER", "Eritrea"},
            {"EE", "Estonia"},
            {"ET", "Ethiopia"},
            {"FK", "Falkland Islands"},
            {"FJ", "Fiji"},
            {"PH", "Philippines"},
            {"FI", "Finland"},
            {"TF", "French Southern Territories"},
            {"FR", "France"},
            {"GA", "Gabon"},
            {"GM", "Gambia"},
            {"GH", "Ghana"},
            {"GI", "Gibraltar"},
            {"GR", "Greece"},
            {"GD", "Grenada"},
            {"GL", "Greenland"},
            {"GE", "Georgia"},
            {"GU", "Guam"},
            {"GY", "Guyana"},
            {"GT", "Guatemala"},
            {"GN", "Guinea"},
            {"GQ", "Equatorial Guinea"},
            {"GW", "Guinea-Bissau"},
            {"HT", "Haiti"},
            {"ES", "Spain"},
            {"HN", "Honduras"},
            {"HK", "Hong Kong"},
            {"IN", "India"},
            {"ID", "Indonesia"},
            {"IQ", "Iraq"},
            {"IR", "Iran"},
            {"IE", "Ireland"},
            {"IS", "Iceland"},
            {"IL", "Israel"},
            {"JM", "Jamaica"},
            {"JP", "Japan"},
            {"YE", "Yemen"},
            {"JO", "Jordan"},
            {"KY", "Cayman Islands"},
            {"KH", "Cambodia"},
            {"CM", "Cameroon"},
            {"CA", "Canada"},
            {"QA", "Qatar"},
            {"KZ", "Kazakhstan"},
            {"KE", "Kenya"},
            {"KG", "Kyrgyztan"},
            {"KI", "Kiribati"},
            {"CO", "Colombia"},
            {"KM", "Comoros"},
            {"CG", "Congo"},
            {"CD", "Democratic Congo"},
            {"KP", "South Korea"},
            {"XK", "Kosovo"},
            {"CR", "Costa Rica"},
            {"CU", "Cuba"},
            {"KW", "Kuwait"},
            {"LA", "Lao"},
            {"LS", "Lesotho"},
            {"LB", "Lebanon"},
            {"LR", "Liberia"},
            {"LY", "Libyan Arab Jamahiriya"},
            {"LI", "Liechtenstein"},
            {"LT", "Lithuania"},
            {"LU", "Luxembourg"},
            {"LV", "Latvia"},
            {"MK", "North Macedonia"},
            {"MG", "Madagascar"},
            {"YT", "Mayotte"},
            {"MO", "Macao"},
            {"MW", "Malawi"},
            {"MV", "Maldives"},
            {"MY", "Malaysia"},
            {"ML", "Mali"},
            {"MT", "Malta"},
            {"MP", "Northern Mariana Islands"},
            {"MA", "Morocco"},
            {"MR", "Mauritania"},
            {"MU", "Mauritius"},
            {"MX", "Mexico"},
            {"XL", "Melilla"},
            {"FM", "Micronesia"},
            {"UM", "U.S. Minor Outlying Islands"},
            {"MD", "Moldova"},
            {"MN", "Mongolia"},
            {"MS", "Montserrat"},
            {"MZ", "Mozambique"},
            {"MM", "Myanmar"},
            {"NA", "Namibia"},
            {"NR", "Nauru"},
            {"NP", "Nepal"},
            {"NL", "Netherlands"},
            {"DE", "Germany"},
            {"NE", "Niger"},
            {"NG", "Nigeria"},
            {"NI", "Nicaragua"},
            {"NU", "Niue"},
            {"NF", "Norfolk Island"},
            {"NO", "Norway"},
            {"NC", "New Caledonia"},
            {"NZ", "New Zealand"},
            {"PS", "Palestinia"},
            {"OM", "Oman"},
            {"PK", "Pakistan"},
            {"PW", "Palau"},
            {"PA", "Panama"},
            {"PG", "Papua New Guinea"},
            {"PY", "Paraguay"},
            {"PE", "Peru"},
            {"PN", "Pitcairn"},
            {"PF", "French Polynesia"},
            {"PL", "Poland"},
            {"ZA", "South Africa"},
            {"GS", "South Georgia and South Sandwich Islands"},
            {"PT", "Portugal"},
            {"KR", "Korea"},
            {"CF", "Central African Republic"},
            {"RU", "Russian Federation"},
            {"RW", "Rwanda"},
            {"EH", "Western Sahara"},
            {"BL", "Saint Barthelemy"},
            {"RO", "Romania"},
            {"SV", "EI Salvador"},
            {"WS", "Samoa"},
            {"AS", "American Samoa"},
            {"SM", "San Marino"},
            {"SN", "Senegal"},
            {"XS", "Serbia"},
            {"SC", "Seychelles"},
            {"SL", "Sierra Leone"},
            {"SG", "Singapore"},
            {"SZ", "Swaziland"},
            {"SK", "Slovakia"},
            {"SI", "Slovenia"},
            {"SO", "Somalia"},
            {"LK", "Sri Lanka"},
            {"PM", "St Pierre and Miquelon"},
            {"KN", "St.Kittsand and Nevis"},
            {"LC", "St.Lucia"},
            {"VC", "St Vincent and the Grenadines"},
            {"US", "United States of America"},
            {"SD", "Sudan"},
            {"SS", "South Sudan"},
            {"SR", "Suriname"},
            {"SY", "Syrian Arab Republic"},
            {"CH", "Switzerland"},
            {"SE", "Sweden"},
            {"SH", "St.Helena"},
            {"TJ", "Tajikistan"},
            {"TH", "Thailand"},
            {"TW", "Taiwan, Provice of China"},
            {"TZ", "Tanzania, United Republic of."},
            {"TG", "Togo"},
            {"TK", "Tokelau"},
            {"TO", "Tonga"},
            {"TT", "Trinidad and Tobago"},
            {"TN", "Tunisia"},
            {"TR", "Turkey"},
            {"TM", "Turkmenistan"},
            {"TC", "Turks and Caicos Islands"},
            {"TV", "Tuvalu"},
            {"UG", "Uganda"},
            {"UA", "Ukraine"},
            {"UY", "Uruguay"},
            {"UZ", "Uzbekistan"},
            {"VU", "Vanuatu"},
            {"WF", "WalIis and Futuna Islands"},
            {"VA", "Vatican City State"},
            {"VE", "Venezuela"},
            {"HU", "Hungary"},
            {"GB", "United Kingdom"},
            {"VN", "Viet - Nam"},
            {"IT", "Italy"},
            {"TL", "Timor Leste"},
            {"CI", "Cote D’Ivoire"},
            {"BV", "Bouvet Island"},
            {"CX", "Christmas Islands"},
            {"CK", "Cook Islands"},
            {"VI", "Virgin Islands (USA)"},
            {"VG", "Virgin Islands (British)"},
            {"HM", "Heard and McDonald Islands"},
            {"CC", "Cocos (Keeling) Islands"},
            {"FO", "Faroe Islands"},
            {"MH", "Marshall Islands"},
            {"SB", "Solomon Islands"},
            {"SX", "Sint Maarten (Dutch part)"},
            {"ST", "Sao Tome and Principe"},
            {"ZM", "Zambia"},
            {"QR", "Stores and provisions within the framework of intra-EU trade"},
            {"CV", "Cape Verde"},
            {"ZW", "Zimbabwe"},
            {"AE", "United Arab Emirates"},
            {"XI", "Northern Ireland"}
    };

    private static final Set<String> VALID_COUNTRIES = new HashSet<>();

    static {
        for (String[] entry : COUNTRIES) {
            VALID_COUNTRIES.add(entry[0].toUpperCase());
            VALID_COUNTRIES.add(entry[1].toUpperCase());
        }
    }

    public static boolean isValidCountry(String input) {
        if (input == null || input.trim().isEmpty()) {
            return false;
        }

        return VALID_COUNTRIES.contains(input.trim().toUpperCase());
    }
}
